

// MDC specific errors
pub const ERRM1: u8 = 1;    // Naked indicator undefined
pub const ERRM2: u8 = 2;    // Invalid $FNUMBER P code string combination
pub const ERRM3: u8 = 3;    // $RANDOM argument less than 1
pub const ERRM4: u8 = 4;    // No true condition in $SELECT
pub const ERRM5: u8 = 5;    // Line reference less than 0
pub const ERRM6: u8 = 6;    // Undefined local variable
pub const ERRM7: u8 = 7;    // Undefined global variable
pub const ERRM8: u8 = 8;    // Undefined special variable
pub const ERRM9: u8 = 9;    // Divide by zero
pub const ERRM10: u8 = 10;  // Invalid pattern match range
pub const ERRM11: u8 = 11;  // No parameters passed
pub const ERRM12: u8 = 12;  // Invalid line reference (negative offset)
pub const ERRM13: u8 = 13;  // Invalid line reference (line not found)
pub const ERRM14: u8 = 14;  // Line level not one
pub const ERRM15: u8 = 15;  // Undefined index variable
pub const ERRM16: u8 = 16;  // QUIT with an argument not allowed
pub const ERRM17: u8 = 17;  // QUIT with an argument required
pub const ERRM18: u8 = 18;  // Fixed length READ not greater than 0
pub const ERRM19: u8 = 19;  // Cannot merge a tree or subtree into itself
pub const ERRM20: u8 = 20;  // Line must have a formal list
pub const ERRM21: u8 = 21;  // Formal list name duplication
pub const ERRM22: u8 = 22;  // SET or KILL to ^$GLOBAL when data in global
pub const ERRM23: u8 = 23;  // SET or KILL to ^$JOB for non-existent job
pub const ERRM25: u8 = 25;  // Attempt to modify currently executing routine
pub const ERRM26: u8 = 26;  // Non-existent environment
pub const ERRM28: u8 = 28;  // Mathematical function, parameter out of range
pub const ERRM29: u8 = 29;  // SET or KILL on SSVN not allowed by implementation
pub const ERRM33: u8 = 33;  // SET or KILL to ^$ROUTINE when routine exists
pub const ERRM35: u8 = 35;  // Device does not support mnemonicspace
pub const ERRM36: u8 = 36;  // Incompatible mnemonicspaces
pub const ERRM37: u8 = 37;  // READ from device identified by the empty string
pub const ERRM38: u8 = 38;  // Invalid SSVN subscript
pub const ERRM39: u8 = 39;  // Invalid $NAME argument
pub const ERRM40: u8 = 40;  // Call-by-reference in JOB actual
pub const ERRM43: u8 = 43;  // Invalid range ($X, $Y)
pub const ERRM45: u8 = 45;  // Invalid GOTO reference
pub const ERRM46: u8 = 46;  // Invalid attribute name
pub const ERRM47: u8 = 47;  // Invalid attribute value
pub const ERRM56: u8 = 56;  // Name length exceeds implementation's limit
pub const ERRM57: u8 = 57;  // More than one defining occurrence of label in routine
pub const ERRM58: u8 = 58;  // Too few formal parameters
pub const ERRM59: u8 = 59;  // Environment reference not permitted for this SSVN
pub const ERRM60: u8 = 60;  // Undefined SSVN
pub const ERRM75: u8 = 75;  // String length exceeds implementation's limit
pub const ERRM92: u8 = 92;  // Mathematical overflow
pub const ERRM93: u8 = 93;  // Mathematical underflow
pub const ERRM99: u8 = 99;  // Invalid operation for context
pub const ERRM101: u8 = 101; // Attempt to assign incorrect value to $ECODE
pub const ERRMLAST: u8 = 200; // Must equal last MDC assigned error

// Implementation specific errors
pub const ERRZ1: u8 = 1;    // Subscript too long (max 127)
pub const ERRZ2: u8 = 2;    // Key too long (max 255)
pub const ERRZ3: u8 = 3;    // Error in key
pub const ERRZ4: u8 = 4;    // Error in database create
pub const ERRZ5: u8 = 5;    // Null character not permitted in key
pub const ERRZ6: u8 = 6;    // Error when reading from database file
pub const ERRZ7: u8 = 7;    // DO stack overflow
pub const ERRZ8: u8 = 8;    // String stack overflow
pub const ERRZ9: u8 = 9;    // Invalid BREAK parameter
pub const ERRZ10: u8 = 10;  // String stack underflow
pub const ERRZ11: u8 = 11;  // Database file is full cannot SET
pub const ERRZ12: u8 = 12;  // Expression syntax error
pub const ERRZ13: u8 = 13;  // Command syntax error
pub const ERRZ14: u8 = 14;  // Unknown opcode encountered
pub const ERRZ15: u8 = 15;  // Too many subscripts
pub const ERRZ16: u8 = 16;  // Null subscript
pub const ERRZ17: u8 = 17;  // Too many IF commands in one line (max 256)
pub const ERRZ18: u8 = 18;  // Unknown external routine
pub const ERRZ19: u8 = 19;  // Too many nested FOR commands (max 256)

// Sequential IO implementation specific errors
pub const ERRZ20: u8 = 20;  // IO: Unknown internal error
pub const ERRZ21: u8 = 21;  // IO: Unrecognised operation
pub const ERRZ22: u8 = 22;  // IO: Timeout < -1
pub const ERRZ23: u8 = 23;  // IO: Operation timed out
pub const ERRZ24: u8 = 24;  // IO: Device not supported
pub const ERRZ25: u8 = 25;  // IO: Channel out of range
pub const ERRZ26: u8 = 26;  // IO: Channel not free
pub const ERRZ27: u8 = 27;  // IO: Channel free
pub const ERRZ28: u8 = 28;  // IO: Unexpected NULL value
pub const ERRZ29: u8 = 29;  // IO: Can not determine object from operation
pub const ERRZ30: u8 = 30;  // IO: Unrecognised object
pub const ERRZ31: u8 = 31;  // IO: Set bit flag out of range
pub const ERRZ33: u8 = 33;  // IO: Number of bytes for buffer out of range
pub const ERRZ34: u8 = 34;  // IO: ASCII character expected
pub const ERRZ35: u8 = 35;  // IO: Unrecognised mode
pub const ERRZ36: u8 = 36;  // IO: Maximum bytes to read < -1
pub const ERRZ37: u8 = 37;  // IO: Read buffer size exceeded
pub const ERRZ38: u8 = 38;  // IO: End of file has been reached
pub const ERRZ39: u8 = 39;  // IO: $KEY too long
pub const ERRZ40: u8 = 40;  // IO: Bytes to write < 0
pub const ERRZ41: u8 = 41;  // IO: Write format specifier < -2
pub const ERRZ42: u8 = 42;  // IO: Maximum number of jobs could be exceeded
pub const ERRZ43: u8 = 43;  // IO: Device not found or a character special dev
pub const ERRZ44: u8 = 44;  // IO: Printf failed
pub const ERRZ45: u8 = 45;  // IO: Unsigned integer value expected
pub const ERRZ46: u8 = 46;  // IO: Peer has disconnected
pub const ERRZ47: u8 = 47;  // IO: Peer not connected
pub const ERRZ48: u8 = 48;  // IO: Invalid Internet address

// More implementation specific errors
pub const ERRZ49: u8 = 49;  // Job table is full
pub const ERRZ50: u8 = 50;  // Invalid argument to $STACK()
pub const ERRZ51: u8 = 51;  // Interrupt - Control-C Received
pub const ERRZ52: u8 = 52;  // Insufficient space to load routine
pub const ERRZ53: u8 = 53;  // Too many tags (max 256)
pub const ERRZ54: u8 = 54;  // Too many lines in routine (max 65534)
pub const ERRZ55: u8 = 55;  // End of linked data reached
pub const ERRZ56: u8 = 56;  // Symbol table full
pub const ERRZ57: u8 = 57;  // Invalid name indirection
pub const ERRZ58: u8 = 58;  // Too many levels of indirection
pub const ERRZ59: u8 = 59;  // Routine version mismatch - please recompile
pub const ERRZ60: u8 = 60;  // Insufficient global buffer space
pub const ERRZ61: u8 = 61;  // Database integrity violation found
pub const ERRZ62: u8 = 62;  // Cannot create global - global directory full
pub const ERRZ63: u8 = 63;  // Error in VIEW arguments
pub const ERRZ64: u8 = 64;  // Parameter out of range
pub const ERRZ65: u8 = 65;  // Duplicate tag in routine
pub const ERRZ66: u8 = 66;  // HUP signal received
pub const ERRZ67: u8 = 67;  // USR1 signal received
pub const ERRZ68: u8 = 68;  // USR2 signal received
pub const ERRZ69: u8 = 69;  // Unknown signal received
pub const ERRZ70: u8 = 70;  // Offset not permitted in entryref
pub const ERRZ71: u8 = 71;  // No such host is known
pub const ERRZ72: u8 = 72;  // Type h_errno error has occurred
pub const ERRZ73: u8 = 73;  // Invalid database file specified
pub const ERRZ74: u8 = 74;  // Too many variables (max 255)
pub const ERRZ75: u8 = 75;  // Too many arguments (max 127)
pub const ERRZ77: u8 = 77;  // RSM is in restricted mode
pub const ERRZ78: u8 = 78;  // Lock count exceeds implementation's limit
pub const ERRZLAST: u8 = 200; // Must equal last implementation error

// Database dummy errors
pub const USRERR: i16 = -9999;